spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 9527
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true